const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("posAPI", {
  login: (payload) => ipcRenderer.invoke("auth:login", payload),
  listMenu: (payload) => ipcRenderer.invoke("menu:list", payload),
  createMenuItem: (payload) => ipcRenderer.invoke("menu:create", payload),
  updateMenuItem: (payload) => ipcRenderer.invoke("menu:update", payload),
  listPromotions: () => ipcRenderer.invoke("promotions:list"),
  createPromotion: (payload) => ipcRenderer.invoke("promotions:create", payload),
  updatePromotion: (payload) => ipcRenderer.invoke("promotions:update", payload),

  createOrder: (payload) => ipcRenderer.invoke("orders:create", payload),
  listOpenOrders: (payload) => ipcRenderer.invoke("orders:list-open", payload),
  getOrder: (payload) => ipcRenderer.invoke("orders:get", payload),
  getOrderPayments: (payload) => ipcRenderer.invoke("orders:get-payments", payload),
  addOrderItem: (payload) => ipcRenderer.invoke("orders:add-item", payload),
  updateOrderItemQty: (payload) => ipcRenderer.invoke("orders:update-item-qty", payload),
  updateOrderCustomer: (payload) => ipcRenderer.invoke("orders:update-customer", payload),
  updateOrderDiscount: (payload) => ipcRenderer.invoke("orders:update-discount", payload),
  applyOrderPromo: (payload) => ipcRenderer.invoke("orders:apply-promo", payload),
  clearOrderPromo: (payload) => ipcRenderer.invoke("orders:clear-promo", payload),
  updateOrderStatus: (payload) => ipcRenderer.invoke("orders:update-status", payload),
  addOrderPayment: (payload) => ipcRenderer.invoke("orders:add-payment", payload),
  payOrderCash: (payload) => ipcRenderer.invoke("orders:pay-cash", payload),

  listInventory: () => ipcRenderer.invoke("inventory:list"),
  adjustInventory: (payload) => ipcRenderer.invoke("inventory:adjust", payload),
  purchaseInventory: (payload) => ipcRenderer.invoke("inventory:purchase", payload),
  createIngredient: (payload) => ipcRenderer.invoke("inventory:create-ingredient", payload),
  updateIngredient: (payload) => ipcRenderer.invoke("inventory:update-ingredient", payload),
  createPurchaseOrder: (payload) => ipcRenderer.invoke("procurement:create-po", payload),
  listPurchaseOrders: (payload) => ipcRenderer.invoke("procurement:list-po", payload),
  getPurchaseOrder: (payload) => ipcRenderer.invoke("procurement:get-po", payload),
  receivePurchaseOrder: (payload) => ipcRenderer.invoke("procurement:receive-po", payload),

  openCashSession: (payload) => ipcRenderer.invoke("cash:open-session", payload),
  getOpenCashSession: () => ipcRenderer.invoke("cash:get-open-session"),
  addCashTransaction: (payload) => ipcRenderer.invoke("cash:add-transaction", payload),
  closeCashSession: (payload) => ipcRenderer.invoke("cash:close-session", payload),

  listEmployees: (payload) => ipcRenderer.invoke("employee:list", payload),
  createEmployee: (payload) => ipcRenderer.invoke("employee:create", payload),
  updateEmployee: (payload) => ipcRenderer.invoke("employee:update", payload),
  addEmployeeLedgerEntry: (payload) => ipcRenderer.invoke("employee:add-ledger-entry", payload),
  getEmployeeLedger: (payload) => ipcRenderer.invoke("employee:get-ledger", payload),
  exportEmployeeLedgerCsv: (payload) => ipcRenderer.invoke("employee:export-ledger-csv", payload),
  deleteEmployeeLedgerEntry: (payload) => ipcRenderer.invoke("employee:delete-ledger-entry", payload),
  closeEmployeeCurrentMonth: (payload) => ipcRenderer.invoke("employee:close-current-month", payload),

  listKitchenTickets: (payload) => ipcRenderer.invoke("kds:list", payload),
  updateKitchenTicketStatus: (payload) => ipcRenderer.invoke("kds:update-status", payload),
  bumpKitchenTicket: (payload) => ipcRenderer.invoke("kds:bump", payload),

  getReportSummary: (payload) => ipcRenderer.invoke("reports:summary", payload),
  getProcurementReport: () => ipcRenderer.invoke("reports:procurement"),
  getDailyRegister: () => ipcRenderer.invoke("reports:daily-register"),
  exportReportCsv: (payload) => ipcRenderer.invoke("reports:export-csv", payload),

  printReceipt: (payload) => ipcRenderer.invoke("system:print-receipt", payload),
  sendKot: (payload) => ipcRenderer.invoke("system:send-kot", payload),
  openCashDrawer: () => ipcRenderer.invoke("system:open-cash-drawer"),
  createBackup: (payload) => ipcRenderer.invoke("system:create-backup", payload),
  listBackups: () => ipcRenderer.invoke("system:list-backups"),
  restoreBackup: (payload) => ipcRenderer.invoke("system:restore-backup", payload),
  getSupabaseStatus: () => ipcRenderer.invoke("system:supabase-status")
});
