-- Supabase schema for Virginia POS
-- Run this in Supabase SQL Editor (project: evrxdojnqvstghregygh).
-- This mirrors the local SQLite schema so main-process upserts by `id` work.

begin;

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  permissions_json text
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  pin_hash text not null,
  role_id bigint not null references public.roles(id),
  active integer not null default 1 check (active in (0, 1)),
  created_at text not null default to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null,
  price_cents integer not null,
  active integer not null default 1 check (active in (0, 1))
);

create table if not exists public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  unit text not null,
  stock_qty numeric not null default 0,
  unit_cost_cents integer not null default 0,
  low_stock_threshold numeric not null default 0,
  supplier text,
  updated_at text not null default to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  menu_item_id bigint not null references public.menu_items(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  qty_per_item numeric not null,
  unique (menu_item_id, ingredient_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('DRAFT', 'HOLD', 'CANCELLED', 'FINALIZED', 'PAID')),
  subtotal_cents integer not null default 0,
  discount_cents integer not null default 0,
  tax_cents integer not null default 0,
  total_cents integer not null default 0,
  cashier_user_id bigint not null references public.users(id),
  customer_name text,
  customer_phone text,
  notes text,
  created_at text not null,
  updated_at text not null,
  paid_at text
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id),
  quantity integer not null default 1,
  unit_price_cents integer not null,
  line_total_cents integer not null,
  modifiers_json text
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  method text not null,
  amount_cents integer not null,
  received_cents integer,
  change_cents integer,
  created_at text not null
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  ingredient_id bigint not null references public.ingredients(id),
  movement_type text not null check (movement_type in ('IN', 'OUT')),
  quantity numeric not null,
  reason text not null,
  reference_type text,
  reference_id text,
  user_id bigint references public.users(id),
  created_at text not null
);

create table if not exists public.cash_sessions (
  id bigint generated by default as identity primary key,
  opened_by_user_id bigint not null references public.users(id),
  closed_by_user_id bigint references public.users(id),
  opening_cents integer not null default 0,
  denomination_json text,
  expected_closing_cents integer,
  closing_cents integer,
  variance_cents integer,
  opened_at text not null,
  closed_at text,
  status text not null check (status in ('OPEN', 'CLOSED'))
);

create table if not exists public.cash_transactions (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.cash_sessions(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('IN', 'OUT')),
  amount_cents integer not null,
  reason text not null,
  reference_type text,
  reference_id text,
  user_id bigint references public.users(id),
  created_at text not null
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id),
  action text not null,
  payload_json text,
  created_at text not null
);

-- Grants for Supabase API roles
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant select, insert, update, delete on tables to anon, authenticated;
alter default privileges in schema public grant usage, select on sequences to anon, authenticated;

-- Enable RLS and allow anon/authenticated (desktop app currently uses anon key from main process)
alter table public.roles enable row level security;
alter table public.users enable row level security;
alter table public.menu_items enable row level security;
alter table public.ingredients enable row level security;
alter table public.recipes enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.cash_sessions enable row level security;
alter table public.cash_transactions enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists roles_rw on public.roles;
create policy roles_rw on public.roles for all to anon, authenticated using (true) with check (true);

drop policy if exists users_rw on public.users;
create policy users_rw on public.users for all to anon, authenticated using (true) with check (true);

drop policy if exists menu_items_rw on public.menu_items;
create policy menu_items_rw on public.menu_items for all to anon, authenticated using (true) with check (true);

drop policy if exists ingredients_rw on public.ingredients;
create policy ingredients_rw on public.ingredients for all to anon, authenticated using (true) with check (true);

drop policy if exists recipes_rw on public.recipes;
create policy recipes_rw on public.recipes for all to anon, authenticated using (true) with check (true);

drop policy if exists orders_rw on public.orders;
create policy orders_rw on public.orders for all to anon, authenticated using (true) with check (true);

drop policy if exists order_items_rw on public.order_items;
create policy order_items_rw on public.order_items for all to anon, authenticated using (true) with check (true);

drop policy if exists payments_rw on public.payments;
create policy payments_rw on public.payments for all to anon, authenticated using (true) with check (true);

drop policy if exists inventory_movements_rw on public.inventory_movements;
create policy inventory_movements_rw on public.inventory_movements for all to anon, authenticated using (true) with check (true);

drop policy if exists cash_sessions_rw on public.cash_sessions;
create policy cash_sessions_rw on public.cash_sessions for all to anon, authenticated using (true) with check (true);

drop policy if exists cash_transactions_rw on public.cash_transactions;
create policy cash_transactions_rw on public.cash_transactions for all to anon, authenticated using (true) with check (true);

drop policy if exists audit_logs_rw on public.audit_logs;
create policy audit_logs_rw on public.audit_logs for all to anon, authenticated using (true) with check (true);

commit;

