-- Virginia POS - Supabase PostgreSQL schema
-- Safe to run multiple times.

begin;

set search_path = public;

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  permissions_json text,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  pin_hash text not null,
  role_id bigint not null references public.roles(id),
  active integer not null default 1 check (active in (0, 1)),
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null,
  price_cents integer not null check (price_cents >= 0),
  active integer not null default 1 check (active in (0, 1)),
  created_at timestamptz not null default now()
);

create table if not exists public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  unit text not null,
  stock_qty numeric not null default 0,
  unit_cost_cents integer not null default 0,
  low_stock_threshold numeric not null default 0,
  supplier text,
  updated_at timestamptz not null default now()
);

create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  code text unique,
  name text not null,
  promo_type text not null check (promo_type in ('PERCENT_TOTAL', 'FIXED_TOTAL', 'CATEGORY_PERCENT')),
  value_num numeric not null,
  cap_cents integer,
  category text,
  start_time text,
  end_time text,
  days_mask text,
  active integer not null default 1 check (active in (0, 1)),
  auto_apply integer not null default 0 check (auto_apply in (0, 1)),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('DRAFT', 'HOLD', 'CANCELLED', 'FINALIZED', 'PAID')),
  subtotal_cents integer not null default 0,
  manual_discount_cents integer not null default 0,
  promo_discount_cents integer not null default 0,
  promo_code text,
  promo_id bigint references public.promotions(id),
  discount_cents integer not null default 0,
  tax_cents integer not null default 0,
  total_cents integer not null default 0,
  cashier_user_id bigint not null references public.users(id),
  customer_name text,
  customer_phone text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  menu_item_id bigint not null references public.menu_items(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  qty_per_item numeric not null,
  unique (menu_item_id, ingredient_id)
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id),
  quantity integer not null default 1,
  unit_price_cents integer not null,
  line_total_cents integer not null,
  modifiers_json text
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  method text not null,
  amount_cents integer not null,
  received_cents integer,
  change_cents integer,
  created_at timestamptz not null default now()
);

create table if not exists public.kitchen_tickets (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  status text not null check (status in ('QUEUED', 'PREPARING', 'READY', 'SERVED', 'CANCELLED')),
  notes text,
  bumped_by_user_id bigint references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  ready_at timestamptz,
  served_at timestamptz
);

create table if not exists public.kitchen_ticket_items (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.kitchen_tickets(id) on delete cascade,
  menu_item_id bigint,
  menu_item_name text not null,
  category text,
  quantity integer not null default 1
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  ingredient_id bigint not null references public.ingredients(id),
  movement_type text not null check (movement_type in ('IN', 'OUT')),
  quantity numeric not null,
  reason text not null,
  reference_type text,
  reference_id text,
  user_id bigint references public.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  supplier text not null,
  status text not null check (status in ('OPEN', 'RECEIVED', 'CANCELLED')),
  notes text,
  created_by_user_id bigint references public.users(id),
  total_cost_cents integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  received_at timestamptz
);

create table if not exists public.purchase_order_items (
  id bigint generated by default as identity primary key,
  po_id bigint not null references public.purchase_orders(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id),
  ingredient_name text not null,
  qty_ordered numeric not null,
  qty_received numeric not null default 0,
  unit_cost_cents integer not null default 0,
  line_cost_cents integer not null default 0
);

create table if not exists public.cash_sessions (
  id bigint generated by default as identity primary key,
  opened_by_user_id bigint not null references public.users(id),
  closed_by_user_id bigint references public.users(id),
  opening_cents integer not null default 0,
  denomination_json text,
  expected_closing_cents integer,
  closing_cents integer,
  variance_cents integer,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  status text not null check (status in ('OPEN', 'CLOSED'))
);

create table if not exists public.cash_transactions (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.cash_sessions(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('IN', 'OUT')),
  amount_cents integer not null,
  reason text not null,
  reference_type text,
  reference_id text,
  user_id bigint references public.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id),
  action text not null,
  payload_json text,
  created_at timestamptz not null default now()
);

create table if not exists public.employee_register (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text,
  monthly_salary_cents integer not null default 0 check (monthly_salary_cents >= 0),
  notes text,
  active integer not null default 1 check (active in (0, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.employee_ledger (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employee_register(id) on delete cascade,
  entry_type text not null check (entry_type in ('SALARY', 'CREDIT')),
  amount_cents integer not null check (amount_cents > 0),
  notes text,
  created_by_user_id bigint references public.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.employee_salary_closures (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employee_register(id) on delete cascade,
  month_key text not null,
  base_salary_cents integer not null default 0,
  salary_adjustments_cents integer not null default 0,
  total_salary_cents integer not null default 0,
  credit_cents integer not null default 0,
  net_payable_cents integer not null default 0,
  closed_by_user_id bigint references public.users(id),
  notes text,
  closed_at timestamptz not null default now(),
  unique (employee_id, month_key)
);

create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_updated_at on public.orders(updated_at desc);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_payments_order_id on public.payments(order_id);
create index if not exists idx_payments_created_at on public.payments(created_at desc);
create index if not exists idx_kitchen_tickets_status on public.kitchen_tickets(status);
create index if not exists idx_kitchen_ticket_items_ticket_id on public.kitchen_ticket_items(ticket_id);
create index if not exists idx_inventory_movements_ingredient_id on public.inventory_movements(ingredient_id);
create index if not exists idx_purchase_orders_status on public.purchase_orders(status);
create index if not exists idx_purchase_order_items_po_id on public.purchase_order_items(po_id);
create index if not exists idx_cash_transactions_session_id on public.cash_transactions(session_id);
create index if not exists idx_audit_logs_created_at on public.audit_logs(created_at desc);
create index if not exists idx_employee_register_active on public.employee_register(active);
create index if not exists idx_employee_ledger_employee_id on public.employee_ledger(employee_id);
create index if not exists idx_employee_ledger_created_at on public.employee_ledger(created_at desc);
create index if not exists idx_employee_salary_closures_employee_month on public.employee_salary_closures(employee_id, month_key);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant select, insert, update, delete on tables to anon, authenticated;
alter default privileges in schema public grant usage, select on sequences to anon, authenticated;

alter table public.roles enable row level security;
alter table public.users enable row level security;
alter table public.menu_items enable row level security;
alter table public.ingredients enable row level security;
alter table public.promotions enable row level security;
alter table public.orders enable row level security;
alter table public.recipes enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.kitchen_tickets enable row level security;
alter table public.kitchen_ticket_items enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;
alter table public.cash_sessions enable row level security;
alter table public.cash_transactions enable row level security;
alter table public.audit_logs enable row level security;
alter table public.employee_register enable row level security;
alter table public.employee_ledger enable row level security;
alter table public.employee_salary_closures enable row level security;

drop policy if exists roles_rw on public.roles;
create policy roles_rw on public.roles for all to anon, authenticated using (true) with check (true);

drop policy if exists users_rw on public.users;
create policy users_rw on public.users for all to anon, authenticated using (true) with check (true);

drop policy if exists menu_items_rw on public.menu_items;
create policy menu_items_rw on public.menu_items for all to anon, authenticated using (true) with check (true);

drop policy if exists ingredients_rw on public.ingredients;
create policy ingredients_rw on public.ingredients for all to anon, authenticated using (true) with check (true);

drop policy if exists promotions_rw on public.promotions;
create policy promotions_rw on public.promotions for all to anon, authenticated using (true) with check (true);

drop policy if exists orders_rw on public.orders;
create policy orders_rw on public.orders for all to anon, authenticated using (true) with check (true);

drop policy if exists recipes_rw on public.recipes;
create policy recipes_rw on public.recipes for all to anon, authenticated using (true) with check (true);

drop policy if exists order_items_rw on public.order_items;
create policy order_items_rw on public.order_items for all to anon, authenticated using (true) with check (true);

drop policy if exists payments_rw on public.payments;
create policy payments_rw on public.payments for all to anon, authenticated using (true) with check (true);

drop policy if exists kitchen_tickets_rw on public.kitchen_tickets;
create policy kitchen_tickets_rw on public.kitchen_tickets for all to anon, authenticated using (true) with check (true);

drop policy if exists kitchen_ticket_items_rw on public.kitchen_ticket_items;
create policy kitchen_ticket_items_rw on public.kitchen_ticket_items for all to anon, authenticated using (true) with check (true);

drop policy if exists inventory_movements_rw on public.inventory_movements;
create policy inventory_movements_rw on public.inventory_movements for all to anon, authenticated using (true) with check (true);

drop policy if exists purchase_orders_rw on public.purchase_orders;
create policy purchase_orders_rw on public.purchase_orders for all to anon, authenticated using (true) with check (true);

drop policy if exists purchase_order_items_rw on public.purchase_order_items;
create policy purchase_order_items_rw on public.purchase_order_items for all to anon, authenticated using (true) with check (true);

drop policy if exists cash_sessions_rw on public.cash_sessions;
create policy cash_sessions_rw on public.cash_sessions for all to anon, authenticated using (true) with check (true);

drop policy if exists cash_transactions_rw on public.cash_transactions;
create policy cash_transactions_rw on public.cash_transactions for all to anon, authenticated using (true) with check (true);

drop policy if exists audit_logs_rw on public.audit_logs;
create policy audit_logs_rw on public.audit_logs for all to anon, authenticated using (true) with check (true);

drop policy if exists employee_register_rw on public.employee_register;
create policy employee_register_rw on public.employee_register for all to anon, authenticated using (true) with check (true);

drop policy if exists employee_ledger_rw on public.employee_ledger;
create policy employee_ledger_rw on public.employee_ledger for all to anon, authenticated using (true) with check (true);

drop policy if exists employee_salary_closures_rw on public.employee_salary_closures;
create policy employee_salary_closures_rw on public.employee_salary_closures for all to anon, authenticated using (true) with check (true);

commit;
